service: serverless-loyalty

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  welcome:
    handler: dist/presenters/lambda/welcome.get
    events:
      - http:
          path: welcome
          method: get

  receivePoints:
    handler: dist/presenters/lambda/cashback.receivePoints
    events:
      - http:
          path: cashback/order
          method: post
