service: serverless-loyalty

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  welcome:
    handler: src/presenters/lambda/welcome/handler.get
    events:
      - http:
          path: welcome
          method: get

  receivePoints:
    handler: src/presenters/lambda/cashback/handler.receivePoints
    events:
      - http:
          path: cashback/order
          method: post
